services:
  fastapi:
    build: .
    image: project-dynamic-link-fastapi:local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${APP_DATABASE_URL}
      PYTHONPATH: /app
    ports:
      - "9010:8000"
    volumes:
      - ./src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    networks:
      - backend

networks:
  backend:
    external: true
