"""add user_id in link table

Revision ID: 2921ef8103a0
Revises: 11b44853db4e
Create Date: 2026-03-01 12:08:42.394153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2921ef8103a0'
down_revision: Union[str, Sequence[str], None] = '11b44853db4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'user_id')
    # ### end Alembic commands ###
